apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: default-deny}
spec: {podSelector: {}, policyTypes: [Ingress, Egress]}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: app}
spec:
  podSelector: {matchLabels: {app: temp-log}}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [{namespaceSelector: {matchLabels: {temp-log-access: 'true'}}}]
      ports: [{protocol: TCP, port: 4000}]
  egress:
    - to: [{podSelector: {matchLabels: {app: mongo}}}]
      ports: [{protocol: TCP, port: 27017}]
    - to: [{namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}, podSelector: {matchLabels: {k8s-app: kube-dns}}}]
      ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: mongo}
spec:
  podSelector: {matchLabels: {app: mongo}}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [{podSelector: {matchLabels: {app: temp-log}}}]
      ports: [{protocol: TCP, port: 27017}]
  egress: []
